import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import { Header } from "@/sections/Header";

const neueHaas = localFont({
  src: [
    {
      path: "./font/NeueHaasDisplayRoman.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/NeueHaasDisplayBold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-neueHaas",
});

const saoldisplay = localFont({
  src: [
    {
      path: "./font/SaolDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-saoldisplay",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${neueHaas.variable} ${saoldisplay.variable} antialiased font-neueHaas`}
        >
          <Header />
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
